* Overzicht status datapaper


** Status
	in prep

** location LENTIS data

/usr/people/muntjewe/nobackup/nobackup_1/LENTIS/


** TODOs - figuren

Description figures

1. conceptueel figuur set-up. Data: ECE3_bis timeseries historical + SSP2-4.5
2. Ensemble summary: trend in TAS annual global mean voor hx en sx. Tijdserie en 2D. 
3. GEV Block max PFD + return period, voor TAS en precip. Vergelijken met ERA5
4. Added value of LE's - analyse over # members? of over initialisatie van members (micro/marco perturbation initial conditions)

Demo figures

5. pre-conditioned compound event -  Wheat loss France. Scatter zoals suppl fig 5. Op y-as spring (Apr-Jul) daily avg precip (mm/day), op x-as number of okt-dec days TASMAX between 0-10 degC (#)
6. Nog een voorbeeld, bijv heavy rainfall on already saturated soils - Norway 
7. Impact model - zonne-energie


** TODOs - text 

Description 

1. Introd

2. Methode: (a) model EC3 beschrijving (b) fig 1 + ensemble set-up: voorwaarden (10 jaar voor multi-yr analyses, maar minimale trend daarbinnen) (c) perturbaties beschrij: inital conditions en micro perturbaties

3. LENTIS overzicht (fig 3 and 4)

Demonstratie 
4. per item beschrijf figs 5-7

5.  concl/disc.

